create table archived_internship (id int8 generated by default as identity, internship_id int8, primary key (id))
create table archived_participant (id int8 generated by default as identity, participant_id int8, primary key (id))
create table archived_performance (id int8 generated by default as identity, performance_id int8, primary key (id))
alter table if exists archived_internship add constraint FKpfm920xoxdhes28o4nh66vcq0 foreign key (internship_id) references internship
alter table if exists archived_participant add constraint FKsf6kv24133w2qlq4nmnilua03 foreign key (participant_id) references participants
Hibernate: alter table if exists archived_performance add constraint FKkdpxclvnl22kmhvoc2rnccmjm foreign key (performance_id) references performance